[package]
name = "agent"
version = "0.1.0"
authors = ["David Timm <dtimm@vmware.com>"]
edition = "2018"

[dependencies]
hyper = "0.13"
http = "0.2"
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
log = "0.4"

[dev-dependencies]
tokio-test = "*"
